### ISSUE TITLE
animated stickers are not supported yet

### ISSUE THREAD

**Issue by JuanM04** [vincekruger/flutter_whatsapp_stickers#11]
It throws `animated stickers are not supported yet` when using animated .webp, and my WhatsApp version is `2.20.195.12`

**Comment by vincekruger** [comment]
Whatsapp has not added support for animated stickers to their repository yet.

**Comment by Ola4606** [comment]
hello can anyone please help me in setting up. @vincekruger i keep sending you emails but you ignore me thou.. Hmm i just need like an hour anyone. Cause i am trying to use the flutter plugin to add whatsapp stickers to whatsapp. It adds packs fine but it does not give me the abilit to update them, so i tried other methods and now stickers dont even add anymore and packs are not been created.. Please can anyone get back to me .. 
My gmail: olaoluwaadeyemo7@gmail.com

**Comment by Mastersam07** [comment]
Wanted to ask the update on this issue. Is there a workaround for this with the plugin or it would be added in a future release?

**Comment by vincekruger** [comment]
The plugin will be updated shortly.

**Comment by Mastersam07** [comment]
Thanks. Wanted to know what was up.

**Comment by whopiyush** [comment]
uwu nice, waiting for it <3

**Comment by smappinc** [comment]
following this 👀

**Comment by vincekruger** [comment]
FYI.
If you'd like to test animated stickers please read this
https://github.com/WhatsApp/stickers/wiki/Animated-Stickers

**Comment by whopiyush** [comment]
They're here ![image](https://user-images.githubusercontent.com/18086566/112434752-2890e400-8d01-11eb-837e-5218dfddebd3.png)

**Comment by vincekruger** [comment]
I know :( apologies everyone.  Time is limited.  I'm pushing to get this done this week.

**Comment by whopiyush** [comment]
any updates on this?

**Comment by SAMYAK99** [comment]
> any updates on this?

**Comment by whopiyush** [comment]
:eyes:

**Comment by ghost** [comment]
Any updates?

**Comment by Swapkumbhar31** [comment]
I have added support for animated stickers

[Click here to check Pull Request](https://github.com/vincekruger/flutter_whatsapp_stickers/pull/16)
