### ISSUE TITLE
Error trying to add the sticker pack "requires com.whatsapp.sticker.READ, or grantUriPermission()"

### ISSUE THREAD

**Issue by noxware** [vincekruger/flutter_whatsapp_stickers#12]
E/DatabaseUtils(10150): java.lang.SecurityException: Permission Denial: reading io.github.vincekruger.whatsapp_stickers.StickerContentProvider uri content://com.example.whatsapp_stickers_organizer.stickercontentprovider/metadata/aaa from pid=3627, uid=10169 requires com.whatsapp.sticker.READ, or grantUriPermission()

**Comment by noxware** [comment]
The problem occurred when whatsapp was installed in my sd card. Moving it back to the internal storage fixed the problem but needing to ask each user to move whatsapp back to the internal storage is not a true fix.

Maybe this is related with [this](https://github.com/WhatsApp/stickers/issues/537)

**Comment by vincekruger** [comment]
This is a WhatsApp bug, unfortunately. :(
