### ISSUE TITLE
although I have installed the new version, the message: Pack is not marked as animated pack but contains animated stickers still appears.

### ISSUE THREAD

**Issue by davidsss6** [vincekruger/flutter_whatsapp_stickers#17]
Hi! Congratulations on your efforts to this project. 
Right now I have a doubt. There are any special configuration to use animated stickers?
I try to add one animated sticker using the default project, replacing one of the default images with other of my animateds images, but the error: "pack is not marked as animated pack but contains animated stickers." keeps appearing.

The Whatsapp testing version is 2.21.16.20
I using the ^1.0.1+5 version of flutter_whatsapp_stickers

Thank you!

**Comment by rahulps1000** [comment]
Same issue for me 

my json file contains `"animated_sticker_pack": true,` still its showing `pack is not marked as animated pack but contains animated stickers`

Need to Fix asap

Thanks
