### ISSUE TITLE
Consider merge with https://github.com/applicazza/whatsapp_stickers

### ISSUE THREAD

**Issue by Mesalcode** [vincekruger/flutter_whatsapp_stickers#6]
I would recommend trying to get in contact with applicazza and merge your repos. Than there would finally be  a solution for both android and ios in one.

**Comment by vincekruger** [comment]
Will check this out, but I'm waiting for a decent update for the iOS side before implement.  Right now iOS is a mess.  it works, but it's only one way which is pretty terrible.

https://github.com/applicazza/whatsapp_stickers

**Comment by Mesalcode** [comment]
Great! Hope there will be a good outcome.
